name: deploy
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2.1.2
      - uses: actions/setup-python@v2
      - name: Install aws cli and deploy
        run: pip install awscli
      - run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws configure set region eu-west-3
      - name: npm install
        run: npm install
      - name: build ts
        run: npx webpack --mode production
      - name: zip source
        run: cd .webpack && zip -r deployment.zip *
      - name: deploy to aws
        run: aws lambda update-function-code --function-name books-service --zip-file fileb://.webpack/deployment.zip
